### ISSUE TITLE
[Bug] - Unable to use square brackets in search

### ISSUE THREAD

**Issue by DashwoodIce9** [trygveaa/kitty-kitten-search#8]
Hi,

I am trying to search a log file where log messages begin like so -
1) {Datetime} [INFO] - log_message
2) {Datetime} [ERROR] - log_message
3) {Datetime} [FATAL] - log_message

Sometimes, these keywords `INFO`, `ERROR`, `FATAL` are also in the log_messages, so to filter out the `ERROR` logs I wanted to search for `[ERROR]` as a whole (with square brackets).

The bug is that as soon as I press the square bracket key `[` in the search, the search window crashes (in both literal and regex match modes).
There is some error message printed but it goes away too quickly for me to see what it is. I think the first word in the error message was 'Unterminated'.

Can you please take a look into this? Thanks :)

**Comment by trygveaa** [comment]
The issue with unterminated regexes crashing it should be fixed now. I couldn't reproduce the issue in literal mode though, but please test with the latest commit and see if it works now.

**Comment by DashwoodIce9** [comment]
Just tested. The issue is fixed. Thanks! :)
