### ISSUE TITLE
Search in split layout resizes window

### ISSUE THREAD

**Issue by SecT0uch** [trygveaa/kitty-kitten-search#9]
Thanks for your work, kitty is awesome!

Is this kitten is intended to be run in a split layout ?
The bottom window is getting resized while searching, and not restored back to the initial size after the search.

See the screenshots:
![image](https://user-images.githubusercontent.com/26085417/162416106-034ce1de-f9bf-4363-a92a-e1884e810afb.png)

![image](https://user-images.githubusercontent.com/26085417/162416237-cb1bdd77-bc00-4d3d-805f-676c39cca7c0.png)

![image](https://user-images.githubusercontent.com/26085417/162416350-f56b76c0-a08a-4522-83a2-966c9c8585f1.png)

**Comment by trygveaa** [comment]
This is due to a limitation in kitty, see https://github.com/kovidgoyal/kitty/issues/2391

For now it has to be done this way with split windows. It could probably resize the split window when exiting the search though.
